name: Feature to Develop CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mini-github
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: vuk123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
      env:
        DJANGO_TESTING: 'True'
        DATABASE_HOST: localhost
        DATABASE_NAME: mini-github
        DATABASE_USER: postgres
        DATABASE_PASSWORD: vuk123